# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: load_balancer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'load_balancer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13load_balancer.proto\x12\rload_balancer\"\"\n\rClientRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"(\n\x0eServerResponse\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\",\n\x12ServerRegistration\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\"\'\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"6\n\nLoadReport\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\x12\x10\n\x08\x63pu_load\x18\x02 \x01(\x02\"%\n\x12LoadReportResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x84\x02\n\x0cLoadBalancer\x12J\n\tGetServer\x12\x1c.load_balancer.ClientRequest\x1a\x1d.load_balancer.ServerResponse\"\x00\x12Z\n\x0eRegisterServer\x12!.load_balancer.ServerRegistration\x1a#.load_balancer.RegistrationResponse\"\x00\x12L\n\nReportLoad\x12\x19.load_balancer.LoadReport\x1a!.load_balancer.LoadReportResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'load_balancer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTREQUEST']._serialized_start=38
  _globals['_CLIENTREQUEST']._serialized_end=72
  _globals['_SERVERRESPONSE']._serialized_start=74
  _globals['_SERVERRESPONSE']._serialized_end=114
  _globals['_SERVERREGISTRATION']._serialized_start=116
  _globals['_SERVERREGISTRATION']._serialized_end=160
  _globals['_REGISTRATIONRESPONSE']._serialized_start=162
  _globals['_REGISTRATIONRESPONSE']._serialized_end=201
  _globals['_LOADREPORT']._serialized_start=203
  _globals['_LOADREPORT']._serialized_end=257
  _globals['_LOADREPORTRESPONSE']._serialized_start=259
  _globals['_LOADREPORTRESPONSE']._serialized_end=296
  _globals['_LOADBALANCER']._serialized_start=299
  _globals['_LOADBALANCER']._serialized_end=559
# @@protoc_insertion_point(module_scope)
