# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: load_balancer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'load_balancer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13load_balancer.proto\"8\n\x12ServerRegistration\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"-\n\nLoadUpdate\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0c\n\x04load\x18\x02 \x01(\x05\"\'\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x0f\n\rClientRequest\"(\n\x0eServerResponse\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\"\x1b\n\x0bTaskRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1e\n\x0cTaskResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xac\x01\n\x0cLoadBalancer\x12<\n\x0eRegisterServer\x12\x13.ServerRegistration\x1a\x15.RegistrationResponse\x12,\n\tGetServer\x12\x0e.ClientRequest\x1a\x0f.ServerResponse\x12\x30\n\nReportLoad\x12\x0b.LoadUpdate\x1a\x15.RegistrationResponse25\n\x07\x43ompute\x12*\n\x0bProcessTask\x12\x0c.TaskRequest\x1a\r.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'load_balancer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERREGISTRATION']._serialized_start=23
  _globals['_SERVERREGISTRATION']._serialized_end=79
  _globals['_LOADUPDATE']._serialized_start=81
  _globals['_LOADUPDATE']._serialized_end=126
  _globals['_REGISTRATIONRESPONSE']._serialized_start=128
  _globals['_REGISTRATIONRESPONSE']._serialized_end=167
  _globals['_CLIENTREQUEST']._serialized_start=169
  _globals['_CLIENTREQUEST']._serialized_end=184
  _globals['_SERVERRESPONSE']._serialized_start=186
  _globals['_SERVERRESPONSE']._serialized_end=226
  _globals['_TASKREQUEST']._serialized_start=228
  _globals['_TASKREQUEST']._serialized_end=255
  _globals['_TASKRESPONSE']._serialized_start=257
  _globals['_TASKRESPONSE']._serialized_end=287
  _globals['_LOADBALANCER']._serialized_start=290
  _globals['_LOADBALANCER']._serialized_end=462
  _globals['_COMPUTE']._serialized_start=464
  _globals['_COMPUTE']._serialized_end=517
# @@protoc_insertion_point(module_scope)
