# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\"b\n\x0ePaymentRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_account\x18\x02 \x01(\t\x12\x12\n\nto_account\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\"\"\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"b\n\x0ePrepareRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_account\x18\x02 \x01(\t\x12\x12\n\nto_account\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\"\x14\n\x04Vote\x12\x0c\n\x04vote\x18\x01 \x01(\x08\"\'\n\rCommitRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"&\n\x0c\x41\x62ortRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32m\n\x0ePaymentGateway\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponse\x12\x33\n\x0eProcessPayment\x12\x0f.PaymentRequest\x1a\x10.PaymentResponse2g\n\x04\x42\x61nk\x12!\n\x07Prepare\x12\x0f.PrepareRequest\x1a\x05.Vote\x12\x1e\n\x06\x43ommit\x12\x0e.CommitRequest\x1a\x04.Ack\x12\x1c\n\x05\x41\x62ort\x12\r.AbortRequest\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=17
  _globals['_LOGINREQUEST']._serialized_end=67
  _globals['_LOGINRESPONSE']._serialized_start=69
  _globals['_LOGINRESPONSE']._serialized_end=99
  _globals['_PAYMENTREQUEST']._serialized_start=101
  _globals['_PAYMENTREQUEST']._serialized_end=199
  _globals['_PAYMENTRESPONSE']._serialized_start=201
  _globals['_PAYMENTRESPONSE']._serialized_end=235
  _globals['_PREPAREREQUEST']._serialized_start=237
  _globals['_PREPAREREQUEST']._serialized_end=335
  _globals['_VOTE']._serialized_start=337
  _globals['_VOTE']._serialized_end=357
  _globals['_COMMITREQUEST']._serialized_start=359
  _globals['_COMMITREQUEST']._serialized_end=398
  _globals['_ABORTREQUEST']._serialized_start=400
  _globals['_ABORTREQUEST']._serialized_end=438
  _globals['_ACK']._serialized_start=440
  _globals['_ACK']._serialized_end=462
  _globals['_PAYMENTGATEWAY']._serialized_start=464
  _globals['_PAYMENTGATEWAY']._serialized_end=573
  _globals['_BANK']._serialized_start=575
  _globals['_BANK']._serialized_end=678
# @@protoc_insertion_point(module_scope)
