PROTO_DIR = protofiles
CLIENT_DIR = client
SERVER_DIR = server

PROTO_FILE_GREET = $(PROTO_DIR)/greet.proto
PROTO_OUT_DIR = .

GO_FLAGS = --go_out=$(PROTO_OUT_DIR) --go_opt=paths=source_relative \
           --go-grpc_out=$(PROTO_OUT_DIR) --go-grpc_opt=paths=source_relative

SERVER_PORT = 50051

.PHONY: proto server client clean

proto:
	protoc $(GO_FLAGS) $(PROTO_FILE_GREET)

server:
	go run $(SERVER_DIR)/main.go --port=$(SERVER_PORT)

client:
	go run $(CLIENT_DIR)/main.go

clean:
	rm -f $(PROTO_DIR)/*.pb.go