# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mapreduce.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'mapreduce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapreduce.proto\" \n\x0bTaskRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"]\n\x0eTaskAssignment\x12\x11\n\ttask_type\x18\x01 \x01(\t\x12\x13\n\x0binput_files\x18\x02 \x03(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\x05\x12\x12\n\nnum_reduce\x18\x04 \x01(\x05\"F\n\nTaskResult\x12\x11\n\ttask_type\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\x05\x12\x14\n\x0coutput_files\x18\x03 \x03(\t\"\x1a\n\x07TaskAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32W\n\x06Master\x12(\n\x07GetTask\x12\x0c.TaskRequest\x1a\x0f.TaskAssignment\x12#\n\nSubmitTask\x12\x0b.TaskResult\x1a\x08.TaskAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapreduce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=19
  _globals['_TASKREQUEST']._serialized_end=51
  _globals['_TASKASSIGNMENT']._serialized_start=53
  _globals['_TASKASSIGNMENT']._serialized_end=146
  _globals['_TASKRESULT']._serialized_start=148
  _globals['_TASKRESULT']._serialized_end=218
  _globals['_TASKACK']._serialized_start=220
  _globals['_TASKACK']._serialized_end=246
  _globals['_MASTER']._serialized_start=248
  _globals['_MASTER']._serialized_end=335
# @@protoc_insertion_point(module_scope)
