# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import byzantine_pb2 as byzantine__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in byzantine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ByzantineServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOrder = channel.unary_unary(
                '/ByzantineService/SendOrder',
                request_serializer=byzantine__pb2.OrderRequest.SerializeToString,
                response_deserializer=byzantine__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.ForwardOrder = channel.unary_unary(
                '/ByzantineService/ForwardOrder',
                request_serializer=byzantine__pb2.ForwardRequest.SerializeToString,
                response_deserializer=byzantine__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.GetOrders = channel.unary_unary(
                '/ByzantineService/GetOrders',
                request_serializer=byzantine__pb2.GetOrdersRequest.SerializeToString,
                response_deserializer=byzantine__pb2.GetOrdersResponse.FromString,
                _registered_method=True)


class ByzantineServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """New method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ByzantineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOrder,
                    request_deserializer=byzantine__pb2.OrderRequest.FromString,
                    response_serializer=byzantine__pb2.OrderResponse.SerializeToString,
            ),
            'ForwardOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardOrder,
                    request_deserializer=byzantine__pb2.ForwardRequest.FromString,
                    response_serializer=byzantine__pb2.ForwardResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=byzantine__pb2.GetOrdersRequest.FromString,
                    response_serializer=byzantine__pb2.GetOrdersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ByzantineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ByzantineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ByzantineService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ByzantineService/SendOrder',
            byzantine__pb2.OrderRequest.SerializeToString,
            byzantine__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ByzantineService/ForwardOrder',
            byzantine__pb2.ForwardRequest.SerializeToString,
            byzantine__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ByzantineService/GetOrders',
            byzantine__pb2.GetOrdersRequest.SerializeToString,
            byzantine__pb2.GetOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
