# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: byzantine.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'byzantine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x62yzantine.proto\"0\n\x0cOrderRequest\x12\r\n\x05order\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\x05\" \n\rOrderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"A\n\x0e\x46orwardRequest\x12\r\n\x05order\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\x05\x12\r\n\x05round\x18\x03 \x01(\x05\"\"\n\x0f\x46orwardResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x12\n\x10GetOrdersRequest\"#\n\x11GetOrdersResponse\x12\x0e\n\x06orders\x18\x01 \x03(\t2\xa5\x01\n\x10\x42yzantineService\x12*\n\tSendOrder\x12\r.OrderRequest\x1a\x0e.OrderResponse\x12\x31\n\x0c\x46orwardOrder\x12\x0f.ForwardRequest\x1a\x10.ForwardResponse\x12\x32\n\tGetOrders\x12\x11.GetOrdersRequest\x1a\x12.GetOrdersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'byzantine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDERREQUEST']._serialized_start=19
  _globals['_ORDERREQUEST']._serialized_end=67
  _globals['_ORDERRESPONSE']._serialized_start=69
  _globals['_ORDERRESPONSE']._serialized_end=101
  _globals['_FORWARDREQUEST']._serialized_start=103
  _globals['_FORWARDREQUEST']._serialized_end=168
  _globals['_FORWARDRESPONSE']._serialized_start=170
  _globals['_FORWARDRESPONSE']._serialized_end=204
  _globals['_GETORDERSREQUEST']._serialized_start=206
  _globals['_GETORDERSREQUEST']._serialized_end=224
  _globals['_GETORDERSRESPONSE']._serialized_start=226
  _globals['_GETORDERSRESPONSE']._serialized_end=261
  _globals['_BYZANTINESERVICE']._serialized_start=264
  _globals['_BYZANTINESERVICE']._serialized_end=429
# @@protoc_insertion_point(module_scope)
